---
title: "Sock Shiny App"
output: html_document
---

This Sock problem began with 1 blog post, _**Given the Tiny dataset of eleven unique socks, how many socks does Karl Broman have in his laundry in total**_, by Karl Broman.

Then, Karl provided the true value of socks -- 21 pairs and 3 singletons.

Since we only have tiny dataset, we need to use ABC (Approximate Bayesian Computation) to build a generative model which simulates the picking-socks process and then derives the expected number of socks.

### General Settings

We try to create a interactive platform derived from original question which allows users to manipulate the parameters.

#### Iterations
First, we set a `numericInput` which lets the users to choose how many times they are going to simulate and store it into `n_sims`.

#### Input observed data (total number fixed to be 11)
Given that we are imitating a tiny data set problem, we restrict the number of observed socks to be 11. It can be 11 singletons, or it can be 4 pairs and 3 odds. To implement this, we build a `sliderInput` which allows the users to decided how many singleton socks they pick from the laundry, which is `n_odds`. Since the number of picked socks have been determined at this time, such as 11, the number of paired socks will be calculated accordingly. Therefore, we build a `verbatimTextOutput` to show the number of paired socks (`n_pairs`). In addition, we have the restriction on the `n_odds` so that the `n_pairs ` is the even number. 

#### Prior parameters and restrictions
Then, we start processing prior parameters.

First, we let the users choose the **prior on the total number of socks** by using `selectInput`. The options are **Negative Binomial**, **Discrete Uniform** and **Poisson**.

**Negative Binomail** uses `sliderInput` to let users choose mean $\mu$ - "expected total number of socks", and standard deviation $\sigma$ - "the expected pair of socks in the laundry", according to Rasmus's explanation in his video. Furthermore, we set restrictions on the parameters. For mean $\mu$, the minimum number will be **11** since 11 socks were picked from the laundry. For standard deviation $\sigma$, its maximum number should be $\left[\frac{\mu}{2}\right]$, according to Rasmus's interpretation of $\sigma$; its minimum should be the maximum of the number of paired socks picked (input by the user) or $(\left[\sqrt{\mu}\right]+1)$ ($\mu$ input by the user), because we should have the size of negative binomial $\text{size}=\frac{-\mu^{2}}{\mu-\sigma^{2}} > 0$.

**Discrete Uniform** has a `sliderInput` to let users choose the parameters -- minimum and maximum, and sample uniformly and discretely (only integer values).

**Poisson** let users choose $\lambda$.

Second, we let the users choose the parameters **prior on proportion of pairs**. We assume the prior on proportion of pairs be **Beta** distribution. The users are able to choose $\alpha$ -- "the number of paired socks", and $\beta$ -- "the number of singleton socks", according to the interpretation from Rasmus in his video.

After setting the **simulation time**, **number of picked socks**, **prior on total number of socks** and **prior on proportion of pairs**, we are ready to simulate **the number of paired**, **the number of odds**, **proportion of pairs**, and **the total number of socks** by implementing ABC. The prior distributions and the posterior distributions will be plotted.

We set 6 check boxes by `checkboxInput`. The check boxes let the users decide whether or not to show the extra information. The options are medians, 95% credit intervals, true value.

### Data Simulating

By obtaining the value of parameters from the users, we are able to simulate the number of total socks. The process is to simulate a total number of socks by the prior distribution and immitate the picking-process to pick 11 socks. The variable `sim_pair` is the simulate number of paired socks that we pick. The variable `sim_odds` is the simulate number of singleton socks that we pick. Then, we use `replicate` which replicates the process `n_sims` times.

Next process is to derive the posteriors from the prior. By using ABC method, we keep the data which `sim_odds` matches the `n_odds` (user input of the number of odds) and `sim_pairs` matches the `n_pairs` (user input of the number of pairs).

### How's Our Performance?

We plot 4 distributions, which are **total number of socks**, **number of paired socks**, **number of singleton socks** and **proportion of paired socks**. In each graph, we provide both prior and posterior distributions. For each of the graph, the users are able to choose whether or not to plot extra information, median of posterior sample, 95% credit intervals, true value, posterior summary statistics and prior summary statistics. 

When we use the same parameters that provided from the blog:

When the number of singleton socks is set to 11; the parameters of negative binomial are set to be $\mu=30$ and $\sigma=15$; the parameters of beta distribution are set to be $\alpha=15$ and $\beta=30$, the median of the total number of socks is 44, with 21 pairs and 3 singletons.

Furthermore, as Rasmus did in his blog, we also test our model on 4 pairs and 3 singletons. The resulting median of total number of socks is 15! Hurray! We got the same result!

## Speed-up

For task 2, we want to test how efficient our code is. In our **ui.R** code, we use `replicate` to simulate the total number of socks. Now, we add more methods, `forloop`, `foreach`, `mclapply` and test how much times they consume individually on the simulation. The codes for comparison are shown below.

`replicate` takes 1.548 second. `forloop` takes 1.366 microsecond. The rest are `foreach`, 2.032, `mc.lapply` with 3 cores, 1.532, and `mc.lapply` with 2 cores, 2.418. However, those values would be various each time when run the code.

However, the processing time would be significantly decreased if we re-define all the input$ parameters, split the replicate function and define a parallel function called (**sock_simulation** in .r file), then we run this function on 4 cores simultaneously 10000 or more times using `mcmapply`. Our interaction surface reacts way faster than before when changing the slider bar.

The replicated are implemented in the ui.r file, so we omitted repeating the code in this writeup.

```{r}
library(parallel)
library(foreach)
#parameters setup
n_sims = 10000
n_pairs = 0
n_odds = 11
nbinom_mu = 30
nbinom_sd = 15
beta_a = 15
beta_b = 30

#prior distribution
prior_size_param = -nbinom_mu^2/(nbinom_mu-nbinom_sd^2)
n_picked = 2 * n_pairs + n_odds

t_socks <- rnbinom(n_sims, mu = nbinom_mu, size = prior_size_param)
prior_pairs <- rbeta(n_sims, shape1 = beta_a, shape2 = beta_b)

t_pairs <- round(floor(t_socks/2) * prior_pairs)
t_odds = t_socks - 2 * t_pairs

t_socks_type = t_pairs + t_odds

socks_sim = matrix(NA, ncol = 6, nrow = n_sims)
colnames(socks_sim) = c("sim_odds", "sim_pairs", "t_socks", "t_pairs", "t_odds", "prior_pairs")

# Replicate
#test the system time for the replication method only
#After 10000 simulation
replicate <- system.time(unlist(replicate(n_sims, { 
  prior_size_param = -nbinom_mu^2 / (nbinom_mu - nbinom_sd^2)
  t_socks <- rnbinom(1, mu = nbinom_mu, size = prior_size_param)
  
  prior_pairs <- rbeta(1, shape1 = beta_a, shape2 = beta_b)
  
  t_pairs <- round(floor(t_socks / 2) * prior_pairs)
  t_odds = t_socks - 2 * t_pairs
  
  n_picked = 2 * n_pairs + n_odds
  socks <- rep(seq_len(t_pairs + t_odds), rep(c(2, 1), c(t_pairs, t_odds)))
  picked_socks <- sample(socks, size =  min(n_picked, t_socks))
  sock_counts <- table(picked_socks)
  socks_sim <- c(sim_odds = sum(sock_counts == 1), sim_pairs = sum(sock_counts == 2),           t_socks = t_socks, t_pairs = t_pairs, t_odds = t_odds, prior_pairs = prior_pairs)
})))

# For loop
#test the system time for the for loop method only
#After 10000 simulation
for.loop <- system.time(unlist(for (i in 1:n_sims) {
  socks = rep(seq_len(t_socks_type[i]), rep(c(2, 1), c(t_pairs[i], t_odds[i])))
  socks_picked = sample(socks,
                        size = min(n_picked, t_socks[i]),
                        replace = TRUE)
  socks_counts = table(socks_picked)
  socks_sim[i, "sim_pairs"] = as.numeric(sum(socks_counts == 2))
  socks_sim[i, "sim_odds"] = as.numeric(sum(socks_counts == 1))
}))

# Foreach
#test the system time for the foreach method only
#After 10000 simulation
for.each <- system.time(unlist(foreach(i = 1:n_sims) %do% function(i) {
  socks = rep(seq_len(t_socks_type[i]), rep(c(2, 1), c(t_pairs[i], t_odds[i])))
  socks_picked = sample(socks,
                        size = min(n_picked, t_socks[i]),
                        replace = TRUE)
  socks_counts = table(socks_picked)
  socks_sim[i, "sim_pairs"] = as.numeric(sum(socks_counts == 2))
  socks_sim[i, "sim_odds"] = as.numeric(sum(socks_counts == 1))
}))

# mclapply with 2 cores
#test the system time for the mclapply with 2 cores method only
#After 10000 simulation
mc.lapply2 <- system.time(unlist(mclapply(1:n_sims, function(i) {
  socks = rep(seq_len(t_socks_type[i]), rep(c(2, 1), c(t_pairs[i], t_odds[i])))
  socks_picked = sample(socks,
                        size = min(n_picked, t_socks[i]),
                        replace = TRUE)
  socks_counts = table(socks_picked)
  socks_sim[i, "sim_pairs"] = as.numeric(sum(socks_counts == 2))
  socks_sim[i, "sim_odds"] = as.numeric(sum(socks_counts == 1))
}, mc.cores = 2)))

# mclapply with 3 cores
#test the system time for the mclapply with 3 cores method only
#After 10000 simulation
mc.lapply3 <- system.time(unlist(mclapply(1:n_sims, function(i) {
  socks = rep(seq_len(t_socks_type[i]), rep(c(2, 1), c(t_pairs[i], t_odds[i])))
  socks_picked = sample(socks,
                        size = min(n_picked, t_socks[i]),
                        replace = TRUE)
  socks_counts = table(socks_picked)
  socks_sim[i, "sim_pairs"] = as.numeric(sum(socks_counts == 2))
  socks_sim[i, "sim_odds"] = as.numeric(sum(socks_counts == 1))
}, mc.cores = 3)))

```